### ISSUE TITLE
No protection against restoring unsupported specturm types.

### ISSUE THREAD

**Issue by rfoxkendo** [FRIBDAQ/SpecTclPythonGUI#13]
This can be triggered e.g. by creating a save set with SPecTcl that has spectsrum types not supported by rustogramer and then reading it in with a rustogramer server.  Note this is likely also possible with conditions.

Error:
```
Traceback (most recent call last):
  File "C:\Users\ron\projects\SpecTclPythonGUI\FileMenu.py", line 220, in _load_definitions
    self._restore_spectra(choice, spectra, existing)
  File "C:\Users\ron\projects\SpecTclPythonGUI\FileMenu.py", line 354, in _restore_spectra
    self._create_spectrum(spectrum)
  File "C:\Users\ron\projects\SpecTclPythonGUI\FileMenu.py", line 439, in _create_spectrum
    name, definition['xparameters'][0], definition['yparameters'][1],
```

**Comment by rfoxkendo** [comment]
This also implies that gate applications can fail ... for example if a condition could not be created or a target spectrum.

**Comment by rfoxkendo** [comment]
The commits above:
* Pop up dialogs for each spectrum that could not be made
* Pop up dialogs for each gate/condition that could not be restored.
* Pops up a dialog indicating which gate applications could not be restored.
